// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gron/internal/biz"
	"gron/internal/conf"
	"gron/internal/data"
	"gron/internal/interfaces"
	"gron/internal/server"
	"gron/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	timerRepo := data.NewGronRepo(dataData)
	timerTaskRepo := data.NewTimerTaskRepo(dataData)
	gronUseCase := biz.NewCreateTimerUseCase(confData, timerRepo, timerTaskRepo)
	gronService := service.NewXTimerService(gronUseCase)
	grpcServer := server.NewGRPCServer(confServer, gronService)
	handler := interfaces.NewHandler(gronService)
	httpServer := server.NewHTTPServer(confServer, handler)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
